name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Already uses v4, but node20 will be forced soon
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Already uses v4, but node20 will be forced soon
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Render
      run: |
        # Trigger deployment (you need the Render API key for this)
        curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        -d '{"serviceId": "srv-crnd58o8fa8c738ds150"}' \
        https://api.render.com/v1/services/srv-crnd58o8fa8c738ds150/deploys

      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
