name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Updated version from v2 to v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Node.js  # Only needed if Node.js-related dependencies exist (e.g., frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Run tests
        run: pytest

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build  # Deploy only if the build succeeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies for deployment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Render
        run: |
          # Trigger deployment (Render API key required)
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '{"serviceId": "srv-crnd58o8fa8c738ds150"}' \
          https://api.render.com/v1/services/srv-crnd58o8fa8c738ds150/deploys

        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
