# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Ensure pytest is installed

      - name: Run tests
        run: pytest  # Run pytest to execute tests

  deploy:
    if: github.ref == 'refs/heads/main'  # Only deploy on main branch
    needs: test  # Ensure tests pass before deployment
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Render
        run: |
          # Trigger deployment using Render API key
          curl -X POST "https://api.render.com/deploy/srv-crnd58o8fa8c738ds150?key=CFb87aKP0MA"


#          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
#          -d '{"serviceId": "srv-crnd58o8fa8c738ds150"}' \
#          https://api.render.com/v1/services/srv-crnd58o8fa8c738ds150/deploys

#        env:
#          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Load the Render API key from GitHub secrets
